INSERT INTO MENU VALUES (1, 'MAIN', 'Schabowy', 15.0);
INSERT INTO MENU VALUES (2, 'SIDE', 'Frytki', 7.0);
INSERT INTO User VALUES(1, '$2a$10$CpULeRv9LsofSMKhWT3sWuwZlrwk9hGByi/qo6ekNAoo0vhfiqjJ2', 'ADMIN', 'admin', NULL, NULL, NULL);
INSERT INTO User VALUES(2, '$2a$10$KEIXP4g1sQmCAT8gE.dDO.4NqgrQ0zzzeDWglkGi0MaTZmd4abr9.', 'CLIENT', 'client', NULL, NULL, NULL);
INSERT INTO User VALUES(3, '$2a$10$jfKiXJdBmXKvN9yuM5e66.tPqZnZTN7xa5DhHYwdJ.jg4Oc90VoTm', 'EMPLOYEE', 'employee', NULL, NULL, NULL);